export {
  DEFAULT_SCORING_CONFIG,
  DEFAULT_STAGE1_WEIGHTS,
  DEFAULT_STAGE1_THRESHOLD,
  DEFAULT_YEARS_MULTIPLIERS,
  DEFAULT_SENIORITY_TIERS,
  DEFAULT_CATEGORY_CEO,
  DEFAULT_CATEGORY_CTO,
  DEFAULT_CATEGORY_COO,
  DEFAULT_CATEGORY_MARKETING,
  DEFAULT_CATEGORY_AI,
  CATEGORY_META,
  PIPELINE_COLUMNS,
} from './config';
export type { AdvisorPipelineId } from './config';
export { computeStage1, computeStage2, scoreAdvisor } from './score';
