// AUTO-GENERATED by sheet-builders/tools/dump_headers_to_ts.py.
// Do not edit by hand. Re-run the dumper whenever a builder's
// *_HEADERS constant changes.
//
// Source of truth: sheet-builders/builders/*.py
// Used by: src/pages/admin/SchemaDoctorPage.tsx (header drift check)

import type { DataKey } from './registry';

export const CANONICAL_HEADERS: Readonly<Record<DataKey, readonly string[]>> = {
  "advisors::activity": ["activity_id", "timestamp", "user_email", "advisor_id", "action", "field", "old_value", "new_value", "details"],
  "advisors::advisors": ["advisor_id", "timestamp", "full_name", "gender", "country", "email", "whatsapp", "linkedin", "tech_rating", "eco_rating", "exp_areas", "exp_detail", "c_level", "c_level_detail", "position", "employer", "years", "non_tech_subjects", "gsg_past", "paid_or_vol", "hourly_rate", "cv_link", "notes", "heard_from", "opportunities", "support_in", "support_via", "tech_specs", "newsletter", "pipeline_status", "assignee_email", "received_ack", "intro_scheduled_date", "intro_done_date", "assessment_date", "decision_date", "tracker_notes", "assignment_company_id", "assignment_intervention_type", "assignment_status", "assignment_notes", "stage1_score", "stage1_pass", "stage2_category", "stage2_score", "updated_at", "updated_by"],
  "advisors::comments": ["comment_id", "advisor_id", "author_email", "body", "visibility", "created_at", "updated_at", "updated_by"],
  "advisors::followups": ["followup_id", "advisor_id", "due_date", "type", "assignee_email", "status", "notes", "created_by", "created_at", "completed_at", "updated_at", "updated_by"],
  "companies::activity": ["activity_id", "timestamp", "user_email", "company_id", "action", "field", "old_value", "new_value", "details"],
  "companies::assignments": ["assignment_id", "company_id", "intervention_type", "sub_intervention", "fund_code", "start_date", "end_date", "owner_email", "status", "budget_usd", "procurement_pr_id", "notes", "updated_at", "updated_by"],
  "companies::comments": ["comment_id", "company_id", "author_email", "body", "created_at", "updated_at"],
  "companies::companies": ["company_id", "company_name", "legal_name", "city", "governorate", "sector", "employee_count", "revenue_bracket", "international_revenue_pct", "readiness_score", "fund_code", "cohort", "status", "stage", "profile_manager_email", "selection_date", "onboarding_date", "primary_contact_id", "drive_folder_url", "notes", "updated_at", "updated_by"],
  "companies::contacts": ["contact_id", "company_id", "full_name", "title", "email", "phone", "is_signatory", "notes", "updated_at", "updated_by"],
  "companies::reviews": ["review_id", "company_id", "reviewer_email", "decision", "proposed_pillars", "proposed_sub_interventions", "notes", "created_at", "updated_at"],
  "companies::statusLog": ["log_id", "company_id", "from_status", "to_status", "changed_at", "changed_by", "reason"],
  "conferences::tracker": ["tracking_id", "company_id", "company_name", "conference_id", "conference_name", "fit_score", "decision", "signatory_name", "signatory_title", "commitment_letter_url", "travel_dates", "flight_booked", "visa_status", "payment_id", "fund_code", "owner_email", "notes", "updated_at", "updated_by"],
  "docs::agreements": ["agreement_id", "company_id", "company_name", "agreement_type", "signed_date", "signatory_name", "signatory_title", "gsg_signatory", "drive_url", "status", "related_intervention", "assignment_id", "notes", "updated_at", "updated_by"],
  "elevateBridge::activity": ["activity_id", "timestamp", "user_email", "entity_type", "entity_id", "action", "field", "old_value", "new_value", "details"],
  "elevateBridge::applicants": ["applicant_id", "full_name_en", "full_name_ar", "email", "phone", "gender", "dob", "location", "region", "specialization", "education_level", "university_name", "university_major", "has_disability", "electricity_reliability", "internet_reliability", "track_registered", "track_assigned", "current_stage", "decision", "killing_factor_result", "killing_factor_reason", "ssi_score", "response_score_fl", "response_score_sm", "interview_score_fl", "interview_score_sm", "total_score", "hours_per_week", "session_commitment", "notes", "updated_at", "updated_by"],
  "elevateBridge::attendance": ["attendance_id", "session_id", "applicant_id", "full_name", "attended", "notes", "updated_at", "updated_by"],
  "elevateBridge::decisions": ["applicant_id", "full_name", "email", "track", "final_score", "decision", "decision_date", "decision_by", "notes"],
  "elevateBridge::interviews": ["interview_id", "applicant_id", "full_name", "track", "q_number", "category", "criterion_label", "weight", "sub_weight", "score", "attended", "notes", "scored_by", "scored_at"],
  "elevateBridge::matches": ["match_id", "applicant_id", "freelancer_name", "freelancer_email", "company_id", "company_name", "track", "status", "hours_per_week", "start_date", "end_date", "notes", "created_by", "created_at", "updated_at", "updated_by"],
  "elevateBridge::mentors": ["mentor_id", "full_name", "email", "whatsapp", "track", "hourly_rate", "total_hours", "budget_total", "bio"],
  "elevateBridge::responses": ["applicant_id", "timestamp", "consent", "safeguarding_ack", "full_name_en", "full_name_ar", "email", "phone", "gender", "dob", "location", "specialization", "education_level", "university_major", "university_name", "disability_details", "how_heard", "track_registered", "session_commitment", "hours_per_week", "raw_blob"],
  "elevateBridge::rubrics": ["rubric_id", "track", "stage", "category", "criterion_key", "criterion_label", "weight", "sub_weight", "score_5", "score_4", "score_3", "score_2", "score_1", "notes"],
  "elevateBridge::sessions": ["session_id", "track", "session_num", "date", "topic", "recording_url", "passcode", "curriculum_url", "hours", "status", "notes", "updated_at", "updated_by"],
  "elevateBridge::stage1": ["applicant_id", "full_name", "email", "phone", "location", "track_registered", "killing_factor_result", "reason", "total_upwork_income_i", "upwork_income_jh", "upwork_income_agency", "sm_income_i", "sm_income_agency", "total_income_normalized", "notes"],
  "elevateBridge::stage2": ["applicant_id", "full_name", "email", "track_registered", "track_assigned", "skills_category", "jh_sector_upwork", "jh_sector_sm", "notes"],
  "elevateBridge::stage3Resp": ["score_id", "applicant_id", "full_name", "track", "category", "criterion_key", "criterion_label", "weight", "sub_weight", "score", "notes", "scored_by", "scored_at"],
  "elevateBridge::stage3Ssi": ["applicant_id", "full_name", "email", "linkedin_url", "ssi_score", "ssi_deadline_met", "notes"],
  "elevateBridge::topPerformers": ["applicant_id", "overall_rank", "city_rank", "area", "track", "full_name_en", "full_name_ar", "email", "phone", "gender", "dob", "location", "specialization", "education_level", "total_earnings", "performance_score", "profile_url", "withdrew"],
  "freelancers::activity": ["activity_id", "timestamp", "user_email", "freelancer_id", "action", "field", "old_value", "new_value", "details"],
  "freelancers::assessments": ["assessment_id", "freelancer_id", "freelancer_name", "assessment_type", "assessor_email", "date", "score", "outcome", "notes"],
  "freelancers::comments": ["comment_id", "freelancer_id", "author_email", "body", "visibility", "created_at", "updated_at", "updated_by"],
  "freelancers::followups": ["followup_id", "freelancer_id", "due_date", "type", "assignee_email", "status", "notes", "created_by", "created_at", "completed_at", "updated_at", "updated_by"],
  "freelancers::freelancers": ["freelancer_id", "full_name", "email", "phone", "location", "track", "role_profile", "assigned_mentor", "company_id", "status", "start_date", "source_sheet", "notes", "assignee_email", "ack_sent", "assessment_date", "decision_date", "tracker_notes", "updated_at", "updated_by"],
  "freelancers::income": ["record_id", "freelancer_id", "freelancer_name", "month", "platform", "gross_income_usd", "verified_by", "verified_at", "notes"],
  "freelancers::tracks": ["assignment_id", "freelancer_id", "freelancer_name", "track", "cohort_group", "mentor_email", "start_date", "end_date", "status", "notes"],
  "payments::payments": ["payment_id", "pr_id", "company_id", "assignment_id", "payee_type", "payee_name", "intervention_type", "fund_code", "amount_usd", "currency", "payment_date", "status", "finance_contact", "invoice_url", "receipt_url", "needs_review", "notes", "updated_at", "updated_by"],
} as const;
